### ISSUE TITLE
SASS Loader module build failed when setting up project

### ISSUE THREAD

**Issue by pablogiralt** [prismicio/slice-machine#78]
### Version

- Prismic CLI version: 3.8.7
- Node version: 10.23.2

### Reproduction

Follow slicemachine quick start instructions:
`npx create-nuxt-app my-slicemachine-project`

Nuxt app setttings:
<img width="669" alt="Screen Shot 2021-02-09 at 18 08 08" src="https://user-images.githubusercontent.com/9419680/107400131-d5245700-6b01-11eb-9c2a-e8946ef50eee.png">
`cd my-slicemachine-project`
`prismic sm --setup`
`yarn dev`

### What is expected?

yarn dev run without errors

### What is actually happening?

<img width="1306" alt="Screen Shot 2021-02-09 at 18 11 12" src="https://user-images.githubusercontent.com/9419680/107400618-3fd59280-6b02-11eb-8f42-840046a31557.png">

```
 ERROR  Failed to compile with 1 errors                                                                                                                        friendly-errors 18:10:53


 ERROR  in ./node_modules/vue-essential-slices/src/slices/PricingTable/index.vue?vue&type=style&index=0&lang=scss&                                             friendly-errors 18:10:53

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):                                                                                             friendly-errors 18:10:53
TypeError: this.getOptions is not a function
    at Object.loader (/Users/pablo/jamstack/my-slicemachine-project/node_modules/sass-loader/dist/index.js:25:24)
                                                                                                                                                               friendly-errors 18:10:53
 @ ./node_modules/vue-style-loader??ref--7-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-essential-slices/src/slices/PricingTable/index.vue?vue&type=style&index=0&lang=scss& 4:14-401 14:3-18:5 15:22-409
 @ ./node_modules/vue-essential-slices/src/slices/PricingTable/index.vue?vue&type=style&index=0&lang=scss&
 @ ./node_modules/vue-essential-slices/src/slices/PricingTable/index.vue
 @ ./node_modules/vue-essential-slices/src/slices lazy ^\.\/.*\.vue$ namespace object
 @ ./.nuxt/prismic/sm-resolver.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js

```

**Comment by pablogiralt** [comment]
ok, so it seems the latest version of sass-loader is not working with latest of vue:
https://stackoverflow.com/questions/66082397/typeerror-this-getoptions-is-not-a-function

I run `yarn add sass-loader@^10.1.1` to fix the issue

**Comment by lihbr** [comment]
Hey @pablogiralt, thanks for your contribution! I'm glad you figured out the issue.

That's quite annoying if every setup leads to this issue now 🤔 I hope they'll fix the issue soon~

@hypervillain perhaps in the meantime, we should pin it there? https://github.com/prismicio/vue-essential-slices/blob/master/sm.config.json#L13

**Comment by lihbr** [comment]
Fixed in https://github.com/prismicio/vue-essential-slices/commit/ab570cd2bc8c527d1b02f275ca4b6f337885089c
Thanks for the report!

**Comment by pablogiralt** [comment]
thanks @lihbr!

**Comment by vbasoon** [comment]
thanks @lihbr!

**Comment by kopax-polyconseil** [comment]
Hi, I have tested all the version from 8 to 11 and I still have this error on a new project. Why is this happening ?

**Comment by lihbr** [comment]
Hey @kopax-polyconseil, I'm sorry to hear that, can you share your complete package.json, node version, and error details please?

**Comment by kopax-polyconseil** [comment]
Thanks for heleping:

```ruby
node -v
v14.13.0
yarn -v
1.22.10
```


I am having the following error when I start my application:

```bash
TypeError: this.getOptions is not a function
```

This is my `devDepednencies`:

```json
{
  "@babel/core": "^7.13.16",
  "@babel/plugin-proposal-export-default-from": "^7.12.13",
  "@babel/preset-env": "^7.13.15",
  "@babel/preset-react": "^7.13.13",
  "@babel/preset-typescript": "^7.13.0",
  "@svgr/webpack": "^5.5.0",
  "@types/node": "^14.14.41",
  "@types/webpack": "^5.28.0",
  "@types/webpack-dev-server": "^3.11.3",
  "babel-loader": "^8.2.2",
  "babel-plugin-named-asset-import": "^0.3.7",
  "babel-preset-react-app": "^10.0.0",
  "camelcase": "^6.2.0",
  "case-sensitive-paths-webpack-plugin": "^2.4.0",
  "copy-webpack-plugin": "^6.4.1",
  "css-loader": "^5.2.4",
  "dotenv": "^8.2.0",
  "dotenv-expand": "^5.1.0",
  "file-loader": "^6.2.0",
  "fork-ts-checker-webpack-plugin": "^6.2.1",
  "fs-extra": "^9.1.0",
  "html-webpack-plugin": "^4.5.2",
  "mini-css-extract-plugin": "^1.5.0",
  "optimize-css-assets-webpack-plugin": "^5.0.4",
  "pnp-webpack-plugin": "^1.6.4",
  "postcss-flexbugs-fixes": "^5.0.2",
  "postcss-loader": "^5.2.0",
  "postcss-normalize": "^9.0.0",
  "postcss-preset-env": "^6.7.0",
  "postcss-safe-parser": "^5.0.2",
  "react-app-polyfill": "^2.0.0",
  "react-dev-utils": "^11.0.4",
  "resolve": "^1.20.0",
  "resolve-url-loader": "^3.1.2",
  "sass": "^1.32.11",
  "sass-loader": "^10.1.1",
  "style-loader": "^2.0.0",
  "terser-webpack-plugin": "^4.2.3",
  "ts-loader": "^9.0.1",
  "ts-node": "^9.1.1",
  "ts-pnp": "^1.2.0",
  "url-loader": "^4.1.1",
  "webpack": "^4.44.2",
  "webpack-cli": "3.3.12",
  "webpack-dev-server": "^3.11.2",
}
```

I have tried to downgrade `postcss-loader` to v4 but then I couldn't get my image assets due to a resolution problem.

I have also tried to downgrade `sass-loader` until v8, without sucesss.


I just want to use sass within a new create-react-app project, how can I do?

**Comment by lihbr** [comment]
Hey thanks! Dumb question maybe but are you actually using [Slice Machine](https://slicemachine.dev)? If not I'd suggest opening an issue on https://github.com/webpack-contrib/sass-loader to get relevant assistance ☺️ The above issue was linked to Slice Machine + Vue.js + SASS

**Comment by kopax-polyconseil** [comment]
Fair enough, I was trying to get some luck here,
Thank you for your replies,
Dimitri

**Comment by lihbr** [comment]
No worries! I would have happily helped you with it but unfortunately I'm not familiar with React and it's been a while since I had to dive into a Webpack config. I think you'll get help there much quicker than here :)

**Comment by iamharshad** [comment]
> ok, so it seems the latest version of sass-loader is not working with latest of vue: https://stackoverflow.com/questions/66082397/typeerror-this-getoptions-is-not-a-function
> 
> I run `yarn add sass-loader@^10.1.1` to fix the issue

In my case latest version is not working with Storybook with React.js but Thanks to you for specifying working version

**Comment by Mohammadnoorcse** [comment]
plz error solve it---


ERROR in ./src/App.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./src/App.scss)

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
3 │ @import "~loaders.css/src/animations/pacman.scss";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\App.scss 3:9  root stylesheet

**Comment by ss252143** [comment]
commonStyle.scss?./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js:1 Uncaught Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: dlopen(/Users/ss252143/Desktop/projects/dbk-mm-sso-ui/ui/node_modules/node-sass/vendor/darwin-arm64-111/binding.node, 0x0001): tried: '/Users/ss252143/Desktop/projects/dbk-mm-sso-ui/ui/node_modules/node-sass/vendor/darwin-arm64-111/binding.node' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/ss252143/Desktop/projects/dbk-mm-sso-ui/ui/node_modules/node-sass/vendor/darwin-arm64-111/binding.node' (no such file), '/Users/ss252143/Desktop/projects/dbk-mm-sso-ui/ui/node_modules/node-sass/vendor/darwin-arm64-111/binding.node' (not a mach-o file)
    at Module._extensions..node (node:internal/modules/cjs/loader:1361:18)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at module.exports (/Users/ss252143/Desktop/projects/dbk-mm-sso-ui/ui/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/Users/ss252143/Desktop/projects/dbk-mm-sso-ui/ui/node_modules/node-sass/lib/index.js:13:35)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at getDefaultSassImplementation (/Users/ss252143/Desktop/projects/dbk-mm-sso-ui/ui/node_modules/sass-loader/dist/utils.js:37:10)
    at getSassImplementation (/Users/ss252143/Desktop/projects/dbk-mm-sso-ui/ui/node_modules/sass-loader/dist/utils.js:46:30)
    at Object.loader (/Users/ss252143/Desktop/projects/dbk-mm-sso-ui/ui/node_modules/sass-loader/dist/index.js:23:55)
    at eval (webpack://mmssoui/./src/features/commonStyles/commonStyle.scss?./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js:1:7)
    at ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/features/commonStyles/commonStyle.scss (http://localhost:3080/main.min.js:1107:1)
    at __webpack_require__ (http://localhost:3080/main.min.js:1668:41)
    at eval (webpack://mmssoui/./src/features/commonStyles/commonStyle.scss?:17:148)
    at ./src/features/commonStyles/commonStyle.scss (http://localhost:3080/main.min.js:1435:1)
    at __webpack_require__ (http://localhost:3080/main.min.js:1668:41)
    at eval (webpack://mmssoui/./src/index.js?:8:97)
    at ./src/index.js (http://localhost:3080/main.min.js:1097:1)
    at __webpack_require__ (http://localhost:3080/main.min.js:1668:41)
    at http://localhost:3080/main.min.js:1947:37
    
    
**Can anyone help in this error?**
